#!/bin/sh
dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
echo "dir: $dir"

ssh_host="isucon4"

rsync -avzc --delete --exclude-from=rsync-exclude-from ${dir}/ ${ssh_host}:webapp

ssh -t -t $ssh_host <<-EOS
  cd /home/isucon/webapp/go
  /home/isucon/env.sh /home/isucon/webapp/go/build.sh

  # sudo sysctl -p
  # sudo service mysqld restart
  sudo service supervisord reload

  sudo service nginx stop
  sudo mv /var/log/nginx/access.log /var/log/nginx/access-$(date '+%F-%T').log
  sudo supervisorctl stop isucon_go
  sudo rm -f /tmp/go.sock
  sudo supervisorctl start isucon_go
  sudo chown nginx:nginx /tmp/go.sock
  sudo service nginx start

  exit
EOS
