#!/bin/sh
#dir=${GIT_DIR:=$(dirname $0)}
dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
echo "dir: $dir"

ssh_host="isucon4"

rsync -avzc --delete --exclude-from=rsync-exclude-from ${dir}/ ${ssh_host}:webapp

ssh -t $ssh_host "cd webapp/go; ./build.sh"
ssh -t $ssh_host "sudo supervisorctl stop isucon_go; sudo rm /tmp/go.sock; sudo supervisorctl start isucon_go; sudo chown nginx:nginx /tmp/go.sock"
